name: smplx
channels:
  - skmad
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libffi=3.4.6
  - liblzma=5.6.4
  - libsqlite=3.48.0
  - libzlib=1.3.1
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.10.16
  - setuptools=75.8.0
  - tk=8.6.13
    #- vc=14.3
    #- vc14_runtime=14.42.34433
  - wheel=0.45.1
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.12
    - aiosignal==1.3.2
    - antlr4-python3-runtime==4.9.3
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - attrs==25.1.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - colorama==0.4.6
    - configargparse==1.7
    - configer
    - configparser==7.1.0
    - contourpy==1.3.1
    - cycler==0.12.1
    - decorator==5.2.1
    - dotmap==1.3.30
    - filelock==3.13.1
    - flatbuffers==25.2.10
    - fonttools==4.56.0
    - freetype-py==2.5.1
    - frozenlist==1.5.0
    - fsspec==2024.6.1
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.70.0
    - h5py==3.13.0
    - idna==3.10
    - imageio==2.37.0
    - imageio-ffmpeg==0.6.0
    - iopath==0.1.10
    - jinja2==3.1.4
    - joblib==1.4.2
    - keras==3.8.0
    - kiwisolver==1.4.8
    - libclang==18.1.1
    - lightning-utilities==0.12.0
    - loguru==0.7.3
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.0
    - mdurl==0.1.2
    - ml-dtypes==0.4.1
    - moviepy==2.2.1
    - mpmath==1.3.0
    - multidict==6.1.0
    - namex==0.0.8
    - networkx==3.3
    - numpy==2.0.2
    - omegaconf==2.3.0
    - open3d-python==0.3.0.0
    - opencv-python==4.11.0.86
    - opt-einsum==3.4.0
    - optree==0.14.0
    - packaging==24.2
    - pandas==2.3.0
    - pillow==11.0.0
    - portalocker==3.1.1
    - proglog==0.1.12
    - propcache==0.2.1
    - protobuf==5.29.3
    - psutil==7.0.0
    - py-cpuinfo==9.0.0
    - pyglet==2.1.2
    - pygments==2.19.1
    - pympi-ling==1.70.2
    - pyopengl==3.1.0
    - pyparsing==3.2.1
    - pyrender==0.1.45
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.0
    - pytorch-lightning==2.5.0.post0
    - pytz==2025.2
      #- pywin32==308
    - pyyaml==6.0.2
    - requests==2.32.3
    - rich==13.9.4
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - shapely==2.0.7
    - six==1.17.0
    - smplx==0.1.28
    - sympy==1.13.1
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.18.0
    - tensorflow-intel
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.5.0
    - threadpoolctl==3.5.0
    - torchgeometry==0.1.2
    - torchmetrics==1.6.1
      #- torchvision==0.21.0+cu118
    - tqdm==4.67.1
    - transforms3d==0.3.1
    - trimesh==4.6.2
    - typing-extensions==4.12.2
    - tzdata==2025.2
    - ultralytics==8.3.162
    - ultralytics-thop==2.0.14
    - urllib3==2.3.0
    - werkzeug==3.1.3
    - win32-setctime==1.2.0
    - wrapt==1.17.2
    - yarl==1.18.3

